"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertTriangle, FileText, Zap, Clock } from "lucide-react";

interface RecoveryDialogProps {
  isOpen: boolean;
  onClose: () => void;
  recoveryData: {
    aiContent?: any;
    backupContent?: any;
    queuedSaves: any[];
    hasRecoveryData: boolean;
  };
  onRecover: (content: any, type: "ai" | "backup" | "queued") => void;
  onDiscard: () => void;
}

export function RecoveryDialog({
  isOpen,
  onClose,
  recoveryData,
  onRecover,
  onDiscard,
}: RecoveryDialogProps) {
  const [selectedRecovery, setSelectedRecovery] = useState<
    "ai" | "backup" | "queued" | null
  >(null);

  const handleRecover = () => {
    if (!selectedRecovery) return;

    let contentToRecover;
    switch (selectedRecovery) {
      case "ai":
        contentToRecover = recoveryData.aiContent;
        break;
      case "backup":
        contentToRecover = recoveryData.backupContent;
        break;
      case "queued":
        contentToRecover = recoveryData.queuedSaves[0]?.content;
        break;
    }

    if (contentToRecover) {
      onRecover(contentToRecover, selectedRecovery);
    }
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-amber-500" />
            Recovery Data Found
          </DialogTitle>
          <DialogDescription>
            We found unsaved content that may have been lost due to connection
            issues. Choose what you'd like to recover:
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {recoveryData.aiContent && (
            <Alert
              className={`cursor-pointer transition-colors ${
                selectedRecovery === "ai"
                  ? "ring-2 ring-blue-500 bg-blue-50"
                  : "hover:bg-gray-50"
              }`}
              onClick={() => setSelectedRecovery("ai")}
            >
              <Zap className="h-4 w-4" />
              <AlertTitle>AI Generated Content</AlertTitle>
              <AlertDescription>
                Content generated by AI that wasn't saved successfully. This is
                usually the most recent and valuable content.
              </AlertDescription>
            </Alert>
          )}

          {recoveryData.backupContent && (
            <Alert
              className={`cursor-pointer transition-colors ${
                selectedRecovery === "backup"
                  ? "ring-2 ring-blue-500 bg-blue-50"
                  : "hover:bg-gray-50"
              }`}
              onClick={() => setSelectedRecovery("backup")}
            >
              <FileText className="h-4 w-4" />
              <AlertTitle>Document Backup</AlertTitle>
              <AlertDescription>
                Automatically backed up document content from your last editing
                session.
              </AlertDescription>
            </Alert>
          )}

          {recoveryData.queuedSaves.length > 0 && (
            <Alert
              className={`cursor-pointer transition-colors ${
                selectedRecovery === "queued"
                  ? "ring-2 ring-blue-500 bg-blue-50"
                  : "hover:bg-gray-50"
              }`}
              onClick={() => setSelectedRecovery("queued")}
            >
              <Clock className="h-4 w-4" />
              <AlertTitle>
                Queued Saves ({recoveryData.queuedSaves.length})
              </AlertTitle>
              <AlertDescription>
                Content that was queued for saving but couldn't be completed due
                to connection issues.
              </AlertDescription>
            </Alert>
          )}
        </div>

        <DialogFooter className="flex gap-2">
          <Button variant="outline" onClick={onDiscard}>
            Discard All
          </Button>
          <Button
            onClick={handleRecover}
            disabled={!selectedRecovery}
            className="bg-blue-600 hover:bg-blue-700"
          >
            Recover Selected
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
